---
- name: Playbook for patching Linux systems
  hosts: all
  become_user: root
  tasks:
    - name: RHEL/Centos systems
      shell: |
              yum clean all
              yum repolist
              yum list-security --security
              yum update --security
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
      register: output
    - debug:
        var: output.stdout_lines
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

    # this task is to restart the system
    - name: restart system
      command: shutdown -r +1  "Rebooting System After Patching"
      async: 0
      poll: 0
      register: reboot_started
      ignore_errors: true

    # this task is to wait for 3 minutues for system to come up after the reboot
    - name: pause for 180 secs
      pause:
        minutes: 3

    # this task is to confirm,system is up and responding to ssh
    - name: check if system responding to ssh
      shell: |
             uptime
             date
             echo "System is Up and New kernel is "
             uname -a
      register: output
    - debug:
        var: output.stdout_lines
